- hosts: all

  become: yes
  become_method: sudo
  remote_user: ubuntu

  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: install haproxy
    apt:
      name: haproxy
      state: present

  - name: Copy haproxy.cfg
    copy:
      src: ./haproxy.cfg
      dest: /etc/haproxy/haproxy.cfg
      owner: root
      group: root
      mode: 0644

  - name: restart haproxy
    command: sudo service haproxy restart

