- hosts: all

  become: yes
  become_method: sudo
  remote_user: ubuntu

  tasks:
  - name: Install aptitude package
    apt:
      name: aptitude
      force_apt_get: yes

  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
      force_apt_get: yes

  - name: install haproxy
    apt:
      name: haproxy
      state: present
      force_apt_get: yes

  - name: Copy haproxy.cfg
    copy:
      src: ./haproxy.cfg
      dest: /etc/haproxy/haproxy.cfg
      owner: tomcat
      group: tomcat
      mode: 0644

  - name: restart haproxy
    service: name=haproxy state=restarted
